- name: catalogue component
  hosts: catalogue
  become: yes
  tasks:
    - name: Setup NodeJS repos
      ansible.builtin.shell: "curl -sL https://rpm.nodesource.com/setup_lts.x | bash"
    
    - name: Install NodeJS
      ansible.builtin.yum:
        name: nodejs
        state: installed
    
    - name: Check if roboshop user exists
      ansible.builtin.shell: id roboshop
      register: out
      ignore_errors: true
    
    - name: Add roboshop user
      ansible.builtin.user:
        name: roboshop
      when: out.rc != 0
    
    - name: Remove /app directory if present
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Unarchive catalogue artifact
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/catalogue.zip 
        dest: /app
        remote_src: yes
    
    - name: Install dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    
    - name: Copy catalogue service file
      ansible.builtin.copy:
        src: ./files/catalogue.service
        dest: /etc/systemd/system/catalogue.service
    
    - name: Restart Catalogue
      ansible.builtin.systemd:
        name: catalogue
        state: restarted
        enabled: true
        daemon_reload: true
    
    - name: Copy MongoDB repo file
      ansible.builtin.copy:
        src: ./files/mongo.repo
        dest: /etc/yum.repos.d/mongo.repo
    
    - name: Install MongoDB Client
      ansible.builtin.yum:
        name: mongodb-org-shell
        state: installed
    
    - name: Import Catalogue Schema
      community.mongodb.mongodb_shell:
        login_host: mongodb-dev.learninguser.online
        file: "/app/schema/catalogue.js"
        idempotent: yes