- name: Dispatch Component
  hosts: dispatch
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.yum:
        name: golang
        state: installed
    
    - name: Add roboshop user
      ansible.builtin.user:
        name: roboshop
      when: out.rc != 0
    
    - name: Remove /app directory if present
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Unarchive dispatch artifact
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/dispatch.zip 
        dest: /app
        remote_src: yes
    
    - name: Install dependencies
      ansible.builtin.shell: "go mod init dispatch; go get; go build"
      args:
        chdir: /app
    
    - name: Copy dispatch service file
      ansible.builtin.copy:
        src: ./files/dispatch.service
        dest: /etc/systemd/system/dispatch.service
    
    - name: Restart dispatch
      ansible.builtin.systemd:
        name: dispatch
        state: restarted
        enabled: true
        daemon_reload: true