- name: Frontend component
  hosts: frontend
  become: yes
  tasks:
    - name: Install NGiNX
      ansible.builtin.yum:
        name: nginx
        state: installed

    - name: Remove default content
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent
    
    - name: create html directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory

    - name: Unarchive frontend artifact
      ansible.builtin.unarchive:
        src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip 
        dest: /usr/share/nginx/html
        remote_src: yes
    
    - name: Copy roboshop.conf file
      ansible.builtin.copy:
        src: ./files/roboshop.conf
        dest: /etc/nginx/default.d/roboshop.conf
    
    - name: Restart NGiNX
      ansible.builtin.systemd:
        name: nginx
        state: restarted
        enabled: true
        daemon_reload: true