- name: Rabbitmq Component
  hosts: rabbitmq
  become: yes
  tasks:
    - name: Configuring YUM repos
      ansible.builtin.shell: "{{ item }}"
      loop:
        - "curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash"
        - "curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash"
    
    - name: Install Rabbitmq server
      ansible.builtin.yum:
        name: rabbitmq-server
        state: installed
    
    - name: Restart Rabbitmq
      ansible.builtin.systemd:
        name: rabbitmq-server
        state: restarted
        enabled: true
        daemon_reload: true

    - name: Add a Roboshop user
      community.rabbitmq.rabbitmq_user:
        user: roboshop
        password: roboshop123
        tags: administrator
        vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
        state: present
